# Python 3 file for generating golden output. 
# ECB mode, padding is PKCS#7
# Example usage: 
#   source myenv/bin/activate
#   python3 generator.py -p 192_plaintext.bin -k 192_key.bin -o test_out.bin
#
# This file was initially generated by google AI and then modified 
# https://share.google/aimode/dDkmrTlAxYw5dRcBK

import argparse
import sys
import time
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad

def main():
    # 1. Setup command line arguments
    parser = argparse.ArgumentParser(
        description="AES ECB Encryption with Zero Padding via file inputs."
    )
    parser.add_argument("-p", "--plaintext", required=True, help="Path to plaintext.bin")
    parser.add_argument("-k", "--key", required=True, help="Path to key.bin")
    parser.add_argument("-o", "--output", required=True, help="Path to save ciphertext output")
    
    args = parser.parse_args()

    # 2. Read input files safely
    try:
        with open(args.plaintext, "rb") as f:
            plaintext_data = f.read()
            
        with open(args.key, "rb") as f:
            key_data = f.read()
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # 3. Validate key size for AES-128, 192, or 256
    key_length = len(key_data)
    #if key_length not in:
    #    print(
    #        f"Error: Invalid key size ({key_length} bytes). "
    #        f"Must be 16 (AES-128), 24 (AES-192), or 32 (AES-256) bytes.", 
    #        file=sys.stderr
    #    )
    #    sys.exit(1)

    # 4. Perform padded encryption
    try:
        cipher = AES.new(key_data, AES.MODE_ECB)
        padded_data = pad(plaintext_data, AES.block_size, style='pkcs7')
        start_time = time.perf_counter()
        ciphertext = cipher.encrypt(padded_data)
        end_time = time.perf_counter()
        
        # 5. Save the result
        with open(args.output, "wb") as f:
            f.write(ciphertext)
            
        print(f"Success! Encrypted file saved to: {args.output}")
        print(f"Detected AES mode variant based on key length: AES-{key_length * 8}")
        print(f"Executed encryption in time: {(end_time - start_time):.6f} seconds")

    except Exception as e:
        print(f"Encryption failed: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()

